// ============================================================
// IFAMDS — Intelligent Forest Advisory & Multi-Structure
//          Decision System
// File   : queues.h
// Layer  : Part 3 — Queue-Based Scheduling Engine
//
// Queue Instances:
//   Q1 — Routine Monitoring Queue      (FIFO — SimpleQueue)
//   Q2 — Continuous Surveillance Queue (FIFO — SimpleQueue)
//   Q3 — Emergency Response Queue      (Max-Heap Priority Queue)
//   Q4 — Multi-Factor Decision Queue   (FIFO — SimpleQueue)
//
// Design:
//   SimpleQueue  — linked-node FIFO, O(1) enqueue/dequeue
//   PriorityQueue— array-based max-heap, O(log n) insert/extract
//   SchedulingEngine — owns all four queues, provides unified API
//
// Authors: Partner A
// Course : CL2001 — Data Structures 2026
// ============================================================

#ifndef QUEUES_H
#define QUEUES_H

#include "constants.h"
#include <string>

// ------------------------------------------------------------
// struct Task
// Represents one unit of work generated by the forest system.
// Created by sensors, anomaly detection, or manual input.
// type codes: "ROUTINE", "SURVEILLANCE", "EMERGENCY", "MULTI"
// ------------------------------------------------------------

struct Task
{
    int         taskId;       // Unique auto-incremented ID
    std::string description;  // Human-readable task description
    int         priority;     // 1–5 (use PriorityLevel enum)
    int         zoneId;       // Forest zone this task applies to
    std::string type;         // Task category string
    bool        isPaused;     // True if queue was paused mid-process
    int         timestamp;    // Logical creation time
};

// ------------------------------------------------------------
// struct QueueNode
// Internal node for SimpleQueue (linked-list FIFO).
// Each node wraps one Task and points to the next node.
// ------------------------------------------------------------

struct QueueNode
{
    Task        data;   // The task stored in this node
    QueueNode*  next;   // Pointer to next node toward tail
};

// ============================================================
// class SimpleQueue
// A linked-list based FIFO queue.
// Enqueue at tail (O(1)), dequeue from head (O(1)).
// Used for Q1 (routine), Q2 (surveillance), Q4 (multi-factor).
// ============================================================

class SimpleQueue
{
private:
    QueueNode*  head;   // Front of queue — next to be dequeued
    QueueNode*  tail;   // Back of queue  — last enqueued
    int         count;  // Current number of tasks in queue
    bool        paused; // Whether this queue is paused

public:

    // Initialises empty queue with head=tail=nullptr, count=0.
    // Time Complexity: O(1)
    SimpleQueue();

    // Destructor — frees all remaining QueueNodes.
    // Time Complexity: O(n)
    ~SimpleQueue();

    // Adds task t to the tail of the queue.
    // Time Complexity: O(1)
    void enqueue(Task t);

    // Removes and returns the task at the head of the queue.
    // Returns a zeroed Task if queue is empty.
    // Time Complexity: O(1)
    Task dequeue();

    // Returns the task at the head without removing it.
    // Time Complexity: O(1)
    Task peek() const;

    // Returns true if the queue has no tasks.
    // Time Complexity: O(1)
    bool isEmpty() const;

    // Returns the current number of tasks in the queue.
    // Time Complexity: O(1)
    int size() const;

    // Sets the paused flag — paused queues skip processing.
    // Time Complexity: O(1)
    void setPaused(bool state);

    // Returns true if this queue is currently paused.
    // Time Complexity: O(1)
    bool isPausedState() const;

    // Prints all tasks in the queue from head to tail.
    // Time Complexity: O(n)
    void display(const std::string& queueName) const;
};

// ============================================================
// class PriorityQueue
// An array-based max-heap priority queue.
// Higher priority value = extracted first (PRIORITY_CRITICAL=5).
// Used exclusively for Q3 (Emergency Response Queue).
//
// Heap property: parent.priority >= children.priority
// Parent of i  : (i-1)/2
// Left child   : 2*i+1
// Right child  : 2*i+2
// ============================================================

class PriorityQueue
{
private:
    Task    heap[MAX_TASKS];  // Heap array — index 0 is root (max priority)
    int     heapSize;         // Current number of elements

    // Moves element at index i upward until heap property restored.
    // Called after insertion at the last position.
    // Time Complexity: O(log n)
    void bubbleUp(int i);

    // Moves element at index i downward until heap property restored.
    // Called after extractMax swaps root with last element.
    // Time Complexity: O(log n)
    void siftDown(int i);

    // Swaps heap[a] and heap[b].
    // Time Complexity: O(1)
    void swapTasks(int a, int b);

public:

    // Initialises empty heap with heapSize=0.
    // Time Complexity: O(1)
    PriorityQueue();

    // Inserts task t into the heap, then bubbles up to restore order.
    // Time Complexity: O(log n)
    void insert(Task t);

    // Removes and returns the highest-priority task (root of heap).
    // Replaces root with last element, then sifts down.
    // Returns zeroed Task if heap is empty.
    // Time Complexity: O(log n)
    Task extractMax();

    // Returns the highest-priority task without removing it.
    // Time Complexity: O(1)
    Task peekMax() const;

    // Returns true if the heap is empty.
    // Time Complexity: O(1)
    bool isEmpty() const;

    // Returns current number of elements in the heap.
    // Time Complexity: O(1)
    int size() const;

    // Prints all tasks currently in the heap (in heap array order).
    // Time Complexity: O(n)
    void display(const std::string& queueName) const;
};

// ============================================================
// class SchedulingEngine
// Owns and manages all four queue instances (Q1–Q4).
// Provides a unified interface for task creation, processing,
// priority switching, load balancing, and pause/resume control.
// ============================================================

class SchedulingEngine
{
private:
    SimpleQueue   q1;           // Q1 — Routine Monitoring (FIFO)
    SimpleQueue   q2;           // Q2 — Continuous Surveillance (FIFO)
    PriorityQueue q3;           // Q3 — Emergency Response (Max-Heap)
    SimpleQueue   q4;           // Q4 — Multi-Factor Decision (FIFO)
    int           taskCounter;  // Auto-incrementing task ID seed

    // Creates a Task struct with auto-assigned ID and timestamp.
    // Time Complexity: O(1)
    Task buildTask(const std::string& desc, int priority,
                   int zone, const std::string& type);

public:

    // Initialises all queues and sets taskCounter to 1.
    // Time Complexity: O(1)
    SchedulingEngine();

    // ========================================================
    // Task Addition Methods
    // ========================================================

    // Creates a PRIORITY_LOW routine task and enqueues it to Q1.
    // Time Complexity: O(1)
    void addRoutineTask(const std::string& desc, int zone);

    // Creates a PRIORITY_MED surveillance task and enqueues to Q2.
    // Time Complexity: O(1)
    void addSurveillanceTask(const std::string& desc, int zone);

    // Creates a PRIORITY_CRITICAL emergency task and inserts to Q3.
    // Time Complexity: O(log n)
    void addEmergencyTask(const std::string& desc, int zone);

    // Creates a PRIORITY_HIGH multi-factor task and enqueues to Q4.
    // Time Complexity: O(1)
    void addMultiFactorTask(const std::string& desc, int zone);

    // ========================================================
    // Task Processing Methods
    // ========================================================

    // Dequeues/extracts and processes the next task from queueId.
    // Prints full task details. Skips if queue is paused or empty.
    // Time Complexity: O(1) for FIFO queues, O(log n) for Q3
    void processNextTask(int queueId);

    // Moves the front task from sourceQueue to targetQueue.
    // Useful for escalating a routine task to emergency.
    // Time Complexity: O(1) or O(log n) depending on target
    void prioritySwitch(int sourceQueue, int targetQueue);

    // Checks all queue sizes and redistributes if Q1 overloads.
    // Rule: if Q1.size() > 10, move 3 tasks to Q2.
    // Prints load status for all queues.
    // Time Complexity: O(n)
    void balanceLoad();

    // ========================================================
    // Pause / Resume Control
    // ========================================================

    // Pauses the specified queue (queueId 1–4).
    // Paused queues refuse processNextTask() calls.
    // Time Complexity: O(1)
    void pauseQueue(int queueId);

    // Resumes a previously paused queue.
    // Time Complexity: O(1)
    void resumeQueue(int queueId);

    // ========================================================
    // Display Methods
    // ========================================================

    // Prints a full dashboard showing all four queues,
    // their sizes, pause states, and task lists.
    // Time Complexity: O(n)
    void displayAllQueues() const;

    // Prints a one-line load summary for all four queues.
    // Time Complexity: O(1)
    void displayLoadSummary() const;

    // Returns the total number of tasks across all queues.
    // Time Complexity: O(1)
    int totalTasks() const;
};

#endif // QUEUES_H
